ALTER TABLE pals ADD COLUMN hp REAL;
ALTER TABLE pals ADD COLUMN gender TEXT NOT NULL DEFAULT '';
ALTER TABLE pals ADD COLUMN talent_hp INTEGER;
ALTER TABLE pals ADD COLUMN talent_melee INTEGER;
ALTER TABLE pals ADD COLUMN talent_shot INTEGER;
ALTER TABLE pals ADD COLUMN talent_defense INTEGER;
ALTER TABLE pals ADD COLUMN passive_skill_ids TEXT NOT NULL DEFAULT '[]';
ALTER TABLE pals ADD COLUMN equipped_skill_ids TEXT NOT NULL DEFAULT '[]';
