CREATE TABLE IF NOT EXISTS game_data_activity (
  at INTEGER PRIMARY KEY,
  fps REAL NOT NULL DEFAULT 0,
  fps_avg REAL NOT NULL DEFAULT 0,
  players INTEGER NOT NULL DEFAULT 0,
  base_pals INTEGER NOT NULL DEFAULT 0,
  linked_base_pals INTEGER NOT NULL DEFAULT 0,
  working INTEGER NOT NULL DEFAULT 0,
  transporting INTEGER NOT NULL DEFAULT 0,
  eating INTEGER NOT NULL DEFAULT 0,
  sleeping INTEGER NOT NULL DEFAULT 0,
  idle INTEGER NOT NULL DEFAULT 0,
  inactive INTEGER NOT NULL DEFAULT 0,
  combat INTEGER NOT NULL DEFAULT 0,
  incapacitated INTEGER NOT NULL DEFAULT 0,
  moving INTEGER NOT NULL DEFAULT 0,
  unknown INTEGER NOT NULL DEFAULT 0
);
